### ISSUE TITLE
Rewrite in a server-side React framework

### ISSUE THREAD

**Issue by fluxehub** [MoreOverMedia/moreoverwebsite#1]
Using a server-side React™ framework such as [Remix™](https://remix.run/), [Next.js™](https://nextjs.org/), or [Gatsby™](https://www.gatsbyjs.com/) allows the site to leverage modern TypeScript™ technologies, and deliver a blazingly-fast interactive experience to users in an optimized bundle. I thus propose rewriting the page in one of these frameworks.

**Comment by MoreOverMedia** [comment]
page has been rewritten using the Next.js[™](https://nextjs.org/) framework. currently working on deploying website via Vercel.

**Comment by fluxehub** [comment]
Wait this was a joke
